import { randomBytes, timingSafeEqual } from "node:crypto";
import type { ChannelConnection } from "@prisma/client";
import { prisma } from "../db";
import { decryptJson, encryptJson } from "../crypto";
import { env } from "../env";
import type { ChannelAdapter, InboundMessage, OutboundMessage, SendResult } from "./types";

/**
 * Telegram Bot API. The first real channel because it needs nobody's approval
 * and proves the whole pipeline end to end (CLAUDE.md §4).
 *
 * Two secrets, and they are NOT the same thing:
 *   - webhookSecret  — the unguessable path segment, generated by Prisma per
 *                      connection. Tells us WHICH connection an update is for.
 *   - secretToken    — sent back to us by Telegram in a header on every update.
 *                      Proves the caller is Telegram and not someone who read
 *                      the URL out of a log or a proxy's access file.
 * The path alone is not authentication; URLs leak.
 */

const API = "https://api.telegram.org";

export interface TelegramCredentials {
  botToken: string;
  secretToken: string;
}

interface TgUser {
  id: number;
  is_bot: boolean;
  first_name?: string;
  last_name?: string;
  username?: string;
  language_code?: string;
}

interface TgChat {
  id: number;
  type: string;
  title?: string;
  username?: string;
}

interface TgMessage {
  message_id: number;
  from?: TgUser;
  chat: TgChat;
  date: number;
  edit_date?: number;
  text?: string;
  caption?: string;
}

interface TgUpdate {
  update_id: number;
  message?: TgMessage;
  edited_message?: TgMessage;
}

/** Every Bot API call. Surfaces Telegram's own `description` — "something went wrong" hides a revoked token. */
async function tgCall<T>(botToken: string, method: string, body?: unknown): Promise<T> {
  const res = await fetch(`${API}/bot${botToken}/${method}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body ?? {}),
  });

  const json = (await res.json().catch(() => null)) as
    | { ok: boolean; result?: T; description?: string; error_code?: number }
    | null;

  if (!json?.ok) {
    // NB: the token is in the URL, never in this message.
    throw new Error(
      `Telegram ${method} failed (${json?.error_code ?? res.status}): ${json?.description ?? res.statusText}`,
    );
  }
  return json.result as T;
}

export function telegramCredentials(connection: ChannelConnection): TelegramCredentials {
  if (!connection.credentialsEnc) {
    throw new Error(`Telegram connection ${connection.id} has no stored credentials.`);
  }
  return decryptJson<TelegramCredentials>(connection.credentialsEnc);
}

/** Constant-time compare — a plain `===` on a secret leaks its prefix by timing. */
export function secretTokenMatches(connection: ChannelConnection, header: string | null): boolean {
  if (!header) return false;
  const expected = Buffer.from(telegramCredentials(connection).secretToken);
  const got = Buffer.from(header);
  return expected.length === got.length && timingSafeEqual(expected, got);
}

export function telegramWebhookUrl(webhookSecret: string): string {
  return `${env.APP_URL.replace(/\/$/, "")}/api/webhooks/telegram/${webhookSecret}`;
}

/**
 * Validate the token, store it encrypted, and point Telegram at us.
 *
 * Reconnecting the SAME bot updates the existing row rather than adding a
 * second one: Telegram allows exactly one webhook per bot, so a duplicate row
 * would own a URL Telegram no longer calls and the channel would look
 * connected while receiving nothing.
 */
export async function connectTelegram(params: {
  organizationId: string;
  botToken: string;
  agentId?: string | null;
  displayName?: string;
}): Promise<{ connection: ChannelConnection; username: string; webhookUrl: string }> {
  const botToken = params.botToken.trim();

  const me = await tgCall<TgUser>(botToken, "getMe");
  const username = me.username ?? String(me.id);

  const existing = await prisma.channelConnection.findFirst({
    where: { organizationId: params.organizationId, kind: "TELEGRAM", externalId: username },
  });

  // Rotated on every connect, and setWebhook is re-run below, so the two sides
  // can never drift out of sync.
  const secretToken = randomBytes(24).toString("hex");
  const credentialsEnc = encryptJson({ botToken, secretToken } satisfies TelegramCredentials);

  const displayName = params.displayName?.trim() || me.first_name || `@${username}`;

  const connection = existing
    ? await prisma.channelConnection.update({
        where: { id: existing.id },
        data: {
          displayName,
          credentialsEnc,
          agentId: params.agentId ?? existing.agentId,
          status: "CONNECTING",
          lastErrorAt: null,
          lastErrorMessage: null,
        },
      })
    : await prisma.channelConnection.create({
        data: {
          organizationId: params.organizationId,
          agentId: params.agentId ?? null,
          kind: "TELEGRAM",
          displayName,
          externalId: username,
          credentialsEnc,
          status: "CONNECTING",
        },
      });

  const webhookUrl = telegramWebhookUrl(connection.webhookSecret);

  try {
    await tgCall(botToken, "setWebhook", {
      url: webhookUrl,
      secret_token: secretToken,
      // Anything not listed here never reaches us, which is most of the volume.
      allowed_updates: ["message", "edited_message"],
      // Whatever piled up while the bot was unconnected is stale by definition;
      // replaying it would answer questions asked days ago.
      drop_pending_updates: true,
      max_connections: 40,
    });
  } catch (e) {
    const message = e instanceof Error ? e.message : String(e);
    await prisma.channelConnection.update({
      where: { id: connection.id },
      data: { status: "FAILED", lastErrorAt: new Date(), lastErrorMessage: message },
    });
    // Telegram refuses http:// and any host it cannot reach, so this is the
    // error every developer hits first.
    const hint = /^https:\/\//.test(env.APP_URL)
      ? ""
      : ` — APP_URL is "${env.APP_URL}"; Telegram requires a public https URL (use a cloudflared/ngrok tunnel in dev).`;
    throw new Error(`${message}${hint}`);
  }

  const active = await prisma.channelConnection.update({
    where: { id: connection.id },
    data: { status: "ACTIVE" },
  });

  return { connection: active, username, webhookUrl };
}

/** Stop Telegram calling us — used when a channel is paused or deleted. */
export async function disconnectTelegram(connection: ChannelConnection): Promise<void> {
  const { botToken } = telegramCredentials(connection);
  await tgCall(botToken, "deleteWebhook", { drop_pending_updates: true });
  await prisma.channelConnection.update({
    where: { id: connection.id },
    data: { status: "PAUSED" },
  });
}

function displayName(u: TgUser | undefined): string | undefined {
  if (!u) return undefined;
  const name = [u.first_name, u.last_name].filter(Boolean).join(" ").trim();
  return name || u.username || undefined;
}

export const telegramAdapter: ChannelAdapter = {
  id: "telegram",

  parseInbound(raw: unknown): InboundMessage | null {
    const update = raw as TgUpdate | null;
    if (!update || typeof update !== "object") return null;

    const edited = Boolean(update.edited_message);
    const m = update.message ?? update.edited_message;
    if (!m?.chat) return null;

    // Our own outbound echo, or another bot in a group. Answering either is a loop.
    if (m.from?.is_bot) return null;

    const text = (m.text ?? m.caption ?? "").trim();
    // Pure media: acknowledging it needs getFile + download + storage, which is
    // a later phase. Returning null is honest — better than persisting an empty
    // turn the agent then tries to answer.
    if (!text) return null;

    const chatId = String(m.chat.id);

    // Stable across redeliveries: Telegram reuses message_id for the same
    // message, and an edit carries its own edit_date so a corrected message is
    // a NEW turn rather than a collision with the original.
    const providerId = edited
      ? `tg:${chatId}:${m.message_id}:e${m.edit_date ?? m.date}`
      : `tg:${chatId}:${m.message_id}`;

    return {
      channel: "telegram",
      providerId,
      // Reply goes to the chat; identity is the person, which differs in groups.
      conversationRef: chatId,
      contact: {
        externalId: String(m.from?.id ?? m.chat.id),
        name: displayName(m.from) ?? m.chat.title,
        locale: m.from?.language_code,
      },
      text: edited ? `(edited) ${text}` : text,
      sentAt: new Date((m.edit_date ?? m.date) * 1000),
      edited,
    };
  },

  async send(connection, to, msg: OutboundMessage): Promise<SendResult> {
    const { botToken } = telegramCredentials(connection);

    const sent = await tgCall<TgMessage>(botToken, msg.mediaUrl ? "sendPhoto" : "sendMessage", {
      chat_id: to,
      ...(msg.mediaUrl ? { photo: msg.mediaUrl, caption: msg.text } : { text: msg.text }),
      link_preview_options: { is_disabled: true },
    });

    // Outbound ids share the inbound namespace and cannot collide — different
    // message_id — so the @@unique on providerId stays safe.
    return { providerId: `tg:${sent.chat.id}:${sent.message_id}` };
  },

  verify(req, connection) {
    return secretTokenMatches(connection, req.headers.get("x-telegram-bot-api-secret-token"));
  },
};

/** "typing…" for ~5s, or until the next message lands. Cheap realism (CLAUDE.md §5). */
export async function sendTyping(connection: ChannelConnection, to: string): Promise<void> {
  const { botToken } = telegramCredentials(connection);
  await tgCall(botToken, "sendChatAction", { chat_id: to, action: "typing" });
}
